import {
  FileText,
  Calendar,
  Pill,
  FlaskConical,
  Heart,
  Camera,
  Receipt,
  ClipboardList,
  User,
} from "lucide-react";

export const patientData = {
  id: "P001",
  name: "John Doe",
  avatar: "/avatars/01.png",
  initials: "JD",
  dob: "1985-03-15",
  age: 39,
  gender: "Male",
  mrn: "MRN-2024-001234",
  admitDate: "2025-08-26",
  dischargeDate: null,
  location: "Room 302B - Medical Floor",
  primaryPhysician: "Dr. Emily Carter",
  contact: {
    phone: "(555) 123-4567",
    email: "john.doe@email.com",
    address: "123 Main St, Anytown, USA 12345",
  },
  allergies: ["Penicillin", "Peanuts"],
  currentMedications: [
    {
      id: "med1",
      name: "Lisinopril",
      dosage: "10mg daily",
      prescribedBy: "Dr. Emily Carter",
      status: "Active",
      pharmacy: {
        name: "CVS Pharmacy",
        phone: "(555) 234-5678",
        address: "456 Oak Ave, Anytown, USA",
      },
    },
    {
      id: "med2",
      name: "Atorvastatin",
      dosage: "20mg daily",
      prescribedBy: "Dr. Emily Carter",
      status: "Active",
      pharmacy: {
        name: "Walgreens",
        phone: "(555) 345-6789",
        address: "789 Pine St, Anytown, USA",
      },
    },
  ],
  recentOrders: [
    {
      id: "ord1",
      name: "Amoxicillin",
      dosage: "500mg, 3x daily for 10 days",
      prescribedBy: "Dr. Emily Carter",
      status: "Completed",
      orderedDate: "2025-08-20",
      pharmacy: {
        name: "CVS Pharmacy",
        phone: "(555) 234-5678",
        address: "456 Oak Ave, Anytown, USA",
      },
    },
    {
      id: "ord2",
      name: "Ibuprofen",
      dosage: "600mg, as needed for pain",
      prescribedBy: "Dr. Robert Johnson",
      status: "Completed",
      orderedDate: "2025-06-15",
    },
  ], // Extended patient information from intake form
  personalInfo: {
    firstName: "John",
    lastName: "Doe",
    dateOfBirth: "1985-03-15",
    gender: "Male",
    phoneNumber: "(555) 123-4567",
    emailAddress: "john.doe@email.com",
    address: "123 Main St",
    city: "Anytown",
    state: "CA",
    zipCode: "12345",
    emergencyContactName: "Jane Doe",
    emergencyContactPhone: "(555) 987-6543",
  },
  insurance: {
    insuranceProvider: "Blue Cross Blue Shield",
    policyNumber: "BC123456789",
    groupNumber: "GRP001",
    policyHolderName: "John Doe",
    policyHolderDob: "1985-03-15",
    relationshipToPatient: "self",
  },
  medicalHistory: {
    primaryCarePhysician: "Dr. Robert Johnson",
    allergies: ["Penicillin", "Peanuts"],
    currentMedications: "Lisinopril 10mg daily, Atorvastatin 20mg daily",
    previousSurgeries: "Appendectomy (2018)",
    familyMedicalHistory: "Father: Hypertension, Mother: Diabetes Type 2",
    smokingStatus: "never",
    alcoholConsumption: "occasional",
    exerciseFrequency: "1-3-week",
  },
  vitals: {
    bp: "120/80 mmHg",
    hr: "72 bpm",
    temp: "98.6°F",
    resp: "16 rpm",
    spo2: "98%",
    recorded: "2025-08-26 08:00",
  },
  labs: [
    { name: "Complete Blood Count", status: "pending", ordered: "2025-08-26" },
    {
      name: "Basic Metabolic Panel",
      status: "completed",
      ordered: "2025-08-25",
      result: "Normal",
    },
    {
      name: "CBC: Hemoglobin",
      status: "completed",
      ordered: "2025-01-15",
      result: "13.8 g/dL",
    },
    {
      name: "CBC: WBC",
      status: "completed",
      ordered: "2025-01-15",
      result: "6.2 K/uL",
    },
    {
      name: "CBC: Platelets",
      status: "completed",
      ordered: "2025-01-15",
      result: "245 K/uL",
    },

    {
      name: "CBC: Hemoglobin",
      status: "completed",
      ordered: "2025-02-15",
      result: "14.0 g/dL",
    },
    {
      name: "CBC: WBC",
      status: "completed",
      ordered: "2025-02-15",
      result: "6.4 K/uL",
    },
    {
      name: "CBC: Platelets",
      status: "completed",
      ordered: "2025-02-15",
      result: "248 K/uL",
    },

    {
      name: "CBC: Hemoglobin",
      status: "completed",
      ordered: "2025-04-12",
      result: "14.3 g/dL",
    },
    {
      name: "CBC: WBC",
      status: "completed",
      ordered: "2025-04-12",
      result: "6.6 K/uL",
    },
    {
      name: "CBC: Platelets",
      status: "completed",
      ordered: "2025-04-12",
      result: "252 K/uL",
    },

    {
      name: "CBC: Hemoglobin",
      status: "completed",
      ordered: "2025-06-20",
      result: "14.4 g/dL",
    },
    {
      name: "CBC: WBC",
      status: "completed",
      ordered: "2025-06-20",
      result: "6.7 K/uL",
    },
    {
      name: "CBC: Platelets",
      status: "completed",
      ordered: "2025-06-20",
      result: "255 K/uL",
    },

    {
      name: "CBC: Hemoglobin",
      status: "completed",
      ordered: "2025-08-18",
      result: "14.6 g/dL",
    },
    {
      name: "CBC: WBC",
      status: "completed",
      ordered: "2025-08-18",
      result: "7.1 K/uL",
    },
    {
      name: "CBC: Platelets",
      status: "completed",
      ordered: "2025-08-18",
      result: "260 K/uL",
    },
  ],
  upcomingAppointments: [
    {
      type: "Follow-up",
      with: "Dr. Carter",
      date: "2025-09-05",
      time: "10:00 AM",
    },
  ],
  appointmentsHistory: [
    {
      id: 1,
      type: "Follow-up",
      with: "Dr. Carter",
      date: "2025-08-12",
      status: "Completed",
    },
    {
      id: 2,
      type: "Initial Consultation",
      with: "Dr. Carter",
      date: "2025-07-20",
      status: "Completed",
    },
  ],
  clinicalNotes: [
    {
      id: 1,
      title: "Follow-up Note",
      author: "Dr. Carter",
      date: "2025-08-12",
      providerType: "physician",
      content:
        "Patient reports improved mood. Continue current medication regimen.",
    },
    {
      id: 2,
      title: "Initial Assessment",
      author: "Dr. Carter",
      date: "2025-07-20",
      providerType: "physician",
      content:
        "New patient presenting with anxiety symptoms. Comprehensive evaluation completed.",
    },
    {
      id: 3,
      title: "Biopsychosocial",
      author: "Dr. Anya Sharma",
      date: "2025-07-21",
      providerType: "therapist",
      content: "Patient discussed family history and social stressors.",
    },
    {
      id: 4,
      title: "Treatment Plan",
      author: "Dr. Emily Carter",
      date: "2025-07-22",
      providerType: "physician",
      content:
        "Initial treatment plan established, focusing on CBT and medication.",
    },
  ],
  billingHistory: [
    {
      id: 1,
      service: "Office Visit (99213)",
      date: "2025-08-12",
      amount: "$150.00",
      status: "Paid",
    },
  ],
};

export const clinicalTabs = [
  { id: "overview", label: "Overview", icon: ClipboardList },
  { id: "patient-info", label: "Patient Information", icon: User },
  { id: "medications", label: "Medications", icon: Pill },
  { id: "labs", label: "Labs & Diagnostics", icon: FlaskConical },
  { id: "notes", label: "Clinical Notes", icon: FileText },
  { id: "vitals", label: "Vitals & Monitoring", icon: Heart },
  { id: "imaging", label: "Imaging", icon: Camera },
  { id: "billing", label: "Billing", icon: Receipt },
];
